Repository terra-rebels/classic-core, pull requests merged in 2022-08, with the labels that each got.

#9 Add basic documentation on how to setup your environment for development
  Makefile
  docs-development/setup.md
Labels: documentation

#14 Removed PR filter on docker.yml workflow
  .github/workflows/docker.yml
Labels: enhancement

#18 changing genesis uri from dropbox to github
  docker/Dockerfile
Labels: enhancement, security
